### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke virtual method 'void 

### ISSUE THREAD

**Issue by SelvaGaneshM** [KingsMentor/Luhn#14]
2018-10-17 10:58:44.540 28560-28560/com.bofin.bank E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bofin.bank, PID: 28560
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.CheckableImageButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at xyz.belvi.luhn.Luhn$4.run(Luhn.java:245)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by KingsMentor** [comment]
fixed on new release
