### ISSUE TITLE
App crashing when trying to invoke startLuhn method

### ISSUE THREAD

**Issue by ramseth001** [KingsMentor/Luhn#21]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.###.app, PID: 9733
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.CheckableImageButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at xyz.belvi.luhn.Luhn$4.run(Luhn.java:259)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7038)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
E/Parcel: Reading a NULL string not supported here.

**Comment by kaushal2406** [comment]
found any solution ? i am also getting same problem .

**Comment by mahbubmukul** [comment]
i am also getting same problem .

**Comment by davidhowe** [comment]
Same, even tried using master SNAPSHOT hoping it would have the fix.
Crash is occurring here:
Luhn.java: 259 -> **Luhn.this.cardNumber.getPasswordToggleView().setOnClickListener...**
